# Generated by Django 5.0.6 on 2024-05-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=300)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
    ]
